/// The one adapter that talks to flutter_rust_bridge-generated code.
///
/// It maps [ElpaBridge] onto the functions generated from `rust/src/api/`. The
/// imports below resolve **after** you run `flutter_rust_bridge_codegen generate`
/// (see the project README), which writes `lib/src/rust/`. Until then this file
/// is the only one that won't analyze — by design, every other Dart file depends
/// on the [ElpaBridge] interface instead.
library;

// Generated by flutter_rust_bridge_codegen. The class name is configured in
// `flutter_rust_bridge.yaml` (`dart_entrypoint_class_name: ElpaRust`).
import 'package:elpa_app/src/rust/frb_generated.dart';
import 'package:elpa_app/src/rust/api/mod.dart' as ffi;

import 'bridge.dart';

/// [ElpaBridge] implemented over the native engine.
class RustElpaBridge implements ElpaBridge {
  RustElpaBridge._();

  /// Initialize the flutter_rust_bridge runtime (loads the dynamic library) and
  /// return a ready bridge. Call once at startup before constructing engines.
  static Future<RustElpaBridge> init() async {
    await ElpaRust.init();
    return RustElpaBridge._();
  }

  ElpaMessage _map(ffi.FfiMessage m) => ElpaMessage(m.channel, m.payload);

  List<ElpaMessage> _mapAll(List<ffi.FfiMessage> msgs) =>
      msgs.map(_map).toList(growable: false);

  ffi.FfiPointer _phase(ElpaPointerPhase p) => switch (p) {
        ElpaPointerPhase.down => ffi.FfiPointer.down,
        ElpaPointerPhase.move => ffi.FfiPointer.move,
        ElpaPointerPhase.up => ffi.FfiPointer.up,
      };

  @override
  Future<ElpaChannels> channels() async => ElpaChannels(
        render: ffi.channelRender(),
        patch: ffi.channelPatch(),
        invalidate: ffi.channelInvalidate(),
        define: ffi.channelDefine(),
        event: ffi.channelEvent(),
      );

  @override
  Future<int?> createFromJs(String jsSource, int width, int height, double scale) async =>
      ffi.createFromJs(jsSource: jsSource, width: width, height: height, scale: scale);

  @override
  Future<int?> createFromBytecode(
          List<int> bytecode, int width, int height, double scale) async =>
      ffi.createFromBytecode(bytecode: bytecode, width: width, height: height, scale: scale);

  @override
  Future<List<ElpaMessage>> start(int handle) async => _mapAll(ffi.start(handle: handle));

  @override
  Future<void> dispose(int handle) async => ffi.dispose(handle: handle);

  @override
  Future<List<ElpaMessage>> pointer(
          int handle, ElpaPointerPhase phase, double x, double y, int button) async =>
      _mapAll(ffi.pointer(handle: handle, phase: _phase(phase), x: x, y: y, button: button));

  @override
  Future<List<ElpaMessage>> wheel(int handle, double x, double y, double deltaY) async =>
      _mapAll(ffi.wheel(handle: handle, x: x, y: y, deltaY: deltaY));

  @override
  Future<List<ElpaMessage>> key(int handle, bool down, String key) async =>
      _mapAll(ffi.key(handle: handle, down: down, key: key));

  @override
  Future<List<ElpaMessage>> frame(int handle, double dtMs) async =>
      _mapAll(ffi.frame(handle: handle, dtMs: dtMs));

  @override
  Future<List<ElpaMessage>> resize(int handle, int width, int height, double scale) async =>
      _mapAll(ffi.resize(handle: handle, width: width, height: height, scale: scale));

  @override
  Future<List<ElpaMessage>> safeArea(
          int handle, double top, double right, double bottom, double left) async =>
      _mapAll(ffi.safeArea(handle: handle, top: top, right: right, bottom: bottom, left: left));

  @override
  Future<List<ElpaMessage>> post(int handle, String channel, String payloadJson) async =>
      _mapAll(ffi.post(handle: handle, channel: channel, payloadJson: payloadJson));

  @override
  Future<List<String>> takeLog(int handle) async => ffi.takeLog(handle: handle);
}
