/// The one adapter that talks to flutter_rust_bridge-generated code.
///
/// It maps [ElpaBridge] onto the functions generated from `rust/src/api/`. The
/// imports below resolve **after** you run `flutter_rust_bridge_codegen generate`
/// (see the project README), which writes `lib/src/rust/`. Until then this file
/// is the only one that won't analyze — by design, every other Dart file depends
/// on the [ElpaBridge] interface instead.
library;

// Generated by flutter_rust_bridge_codegen. The class name is configured in
// `flutter_rust_bridge.yaml` (`dart_entrypoint_class_name: ElpaRust`).
import 'package:elpa_app/src/rust/frb_generated.dart';
// flutter_rust_bridge mirrors the Rust module `crate::api` (a `mod.rs`) onto
// `lib/src/rust/api.dart`, so this is the generated entry point.
import 'package:elpa_app/src/rust/api.dart' as ffi;

import 'bridge.dart';
// Converts an `int` to the type flutter_rust_bridge expects for a Rust `i64`
// parameter (`PlatformInt64`): `int` on native, `BigInt` on web. The conditional
// import mirrors how flutter_rust_bridge itself defines `PlatformInt64`.
import 'raw_handle_native.dart'
    if (dart.library.js_interop) 'raw_handle_web.dart';

/// [ElpaBridge] implemented over the native engine.
class RustElpaBridge implements ElpaBridge {
  RustElpaBridge._();

  /// Initialize the flutter_rust_bridge runtime (loads the dynamic library) and
  /// return a ready bridge. Call once at startup before constructing engines.
  static Future<RustElpaBridge> init() async {
    await ElpaRust.init();
    return RustElpaBridge._();
  }

  ElpaMessage _map(ffi.FfiMessage m) => ElpaMessage(m.channel, m.payload);

  List<ElpaMessage> _mapAll(List<ffi.FfiMessage> msgs) =>
      msgs.map(_map).toList(growable: false);

  // The Rust handle registry is keyed by `u64`, which flutter_rust_bridge maps
  // to Dart `BigInt`. The app talks in plain `int` handles, so this adapter is
  // the single place that converts between the two.
  BigInt _h(int handle) => BigInt.from(handle);

  ffi.FfiPointer _phase(ElpaPointerPhase p) => switch (p) {
        ElpaPointerPhase.down => ffi.FfiPointer.down,
        ElpaPointerPhase.move => ffi.FfiPointer.move,
        ElpaPointerPhase.up => ffi.FfiPointer.up,
      };

  @override
  Future<ElpaChannels> channels() async => ElpaChannels(
        render: ffi.channelRender(),
        patch: ffi.channelPatch(),
        invalidate: ffi.channelInvalidate(),
        define: ffi.channelDefine(),
        event: ffi.channelEvent(),
      );

  @override
  Future<int?> createFromJs(String jsSource, int width, int height, double scale) async =>
      ffi.createFromJs(jsSource: jsSource, width: width, height: height, scale: scale)?.toInt();

  @override
  Future<int?> createFromBytecode(
          List<int> bytecode, int width, int height, double scale) async =>
      ffi
          .createFromBytecode(bytecode: bytecode, width: width, height: height, scale: scale)
          ?.toInt();

  @override
  Future<List<ElpaMessage>> start(int handle) async => _mapAll(ffi.start(handle: _h(handle)));

  @override
  Future<void> dispose(int handle) async {
    ffi.dispose(handle: _h(handle));
  }

  @override
  Future<List<ElpaMessage>> pointer(
          int handle, ElpaPointerPhase phase, double x, double y, int button) async =>
      _mapAll(ffi.pointer(handle: _h(handle), phase: _phase(phase), x: x, y: y, button: button));

  @override
  Future<List<ElpaMessage>> wheel(int handle, double x, double y, double deltaY) async =>
      _mapAll(ffi.wheel(handle: _h(handle), x: x, y: y, deltaY: deltaY));

  @override
  Future<List<ElpaMessage>> key(int handle, bool down, String key) async =>
      _mapAll(ffi.key(handle: _h(handle), down: down, key: key));

  @override
  Future<List<ElpaMessage>> frame(int handle, double dtMs) async =>
      _mapAll(ffi.frame(handle: _h(handle), dtMs: dtMs));

  @override
  Future<List<ElpaMessage>> resize(int handle, int width, int height, double scale) async =>
      _mapAll(ffi.resize(handle: _h(handle), width: width, height: height, scale: scale));

  @override
  Future<List<ElpaMessage>> safeArea(
          int handle, double top, double right, double bottom, double left) async =>
      _mapAll(ffi.safeArea(handle: _h(handle), top: top, right: right, bottom: bottom, left: left));

  @override
  Future<List<ElpaMessage>> post(int handle, String channel, String payloadJson) async =>
      _mapAll(ffi.post(handle: _h(handle), channel: channel, payloadJson: payloadJson));

  @override
  Future<List<String>> takeLog(int handle) async => ffi.takeLog(handle: _h(handle));

  @override
  Future<bool> registerSurface(
    int handle, {
    String canvasId = '',
    int rawHandle = 0,
    int rowStride = 0,
    required int width,
    required int height,
  }) =>
      ffi.registerSurface(
        handle: _h(handle),
        canvasId: canvasId,
        // `raw_handle` is `i64` in Rust. flutter_rust_bridge maps `i64` to a
        // `PlatformInt64` — a plain Dart `int` on native (where `int` is 64-bit)
        // but a `BigInt` on web (where `int` is a 53-bit JS number). Passing a
        // plain `int` compiles on native but fails the web dart2js build, so
        // funnel it through the platform shim that yields the right type for the
        // current target. (The `u64` handles above are `BigInt` on both, hence
        // the simpler `_h`.)
        rawHandle: toRawHandle(rawHandle),
        rowStride: rowStride,
        width: width,
        height: height,
      );
}
